=== YesItIsTrue/repo1/Batch-Runs/Apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_MPA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TK_test_seq"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TK_test_seq">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="test_mstr"/>
        <xs:element ref="people_mstr"/>
        <xs:element ref="patient_mstr"/>
        <xs:element ref="addr_mstr"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="tk_mstr"/>
          <xs:element ref="tkr_det"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="test_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="test_lab_ID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="test_lab_ID" type="xs:NCName"/>
  <xs:element name="people_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="people_lastname"/>
        <xs:element ref="people_firstname"/>
        <xs:element ref="people_midname"/>
        <xs:element ref="people_prefname"/>
        <xs:element ref="people_dob"/>
        <xs:element ref="people_gender"/>
        <xs:element ref="people_ssn"/>
        <xs:element ref="people_homephone"/>
        <xs:element ref="people_workphone"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="people_lastname" type="xs:NCName"/>
  <xs:element name="people_firstname" type="xs:NCName"/>
  <xs:element name="people_midname"/>
  <xs:element name="people_prefname"/>
  <xs:element name="people_dob">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="year"/>
        <xs:element ref="month"/>
        <xs:element ref="day"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="people_gender" type="xs:NCName"/>
  <xs:element name="people_ssn"/>
  <xs:element name="people_homephone"/>
  <xs:element name="people_workphone"/>
  <xs:element name="patient_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="patient_notes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="patient_notes" type="xs:string"/>
  <xs:element name="addr_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="addr_addr1"/>
        <xs:element ref="addr_addr2"/>
        <xs:element ref="addr_city"/>
        <xs:element ref="state_iso"/>
        <xs:element ref="addr_zip"/>
        <xs:element ref="country_iso"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="addr_addr1" type="xs:string"/>
  <xs:element name="addr_addr2" type="xs:string"/>
  <xs:element name="addr_city" type="xs:string"/>
  <xs:element name="state_iso" type="xs:string"/>
  <xs:element name="addr_zip" type="xs:string"/>
  <xs:element name="country_iso" type="xs:string"/>
  <xs:element name="tk_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TK_ID" minOccurs="1"/>
        <xs:element ref="tk_lab_sample_ID" minOccurs="1"/>
        <xs:element name="tk_test_desc"/>
        <xs:element ref="SNP_ID" minOccurs="1"/>
        <xs:element ref="SNP_gene"/>
        <xs:element ref="SNP_variation"/>
        <xs:element ref="coll_begin"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TK_ID">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="tk_lab_sample_ID">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="SNP_ID" type="xs:string"/>
  <xs:element name="SNP_gene" type="xs:string"/>
  <xs:element name="SNP_variation" type="xs:NMTOKEN"/>
  <xs:element name="coll_begin">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="year"/>
        <xs:element ref="month"/>
        <xs:element ref="day"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tkr_det">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="set_id"/>
        <xs:element ref="tkr_item" minOccurs="1"/>
        <xs:element ref="item-check"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="tkr_lab_ref"/>
          <xs:element ref="tkr_lab_results"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="set_id" type="xs:integer"/>
  <xs:element name="tkr_item">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="item-check" type="xs:string"/>
  <xs:element name="tkr_lab_ref" type="xs:string"/>
  <xs:element name="tkr_lab_results" type="xs:string"/>
  <xs:element name="year" type="xs:integer"/>
  <xs:element name="month" type="xs:integer"/>
  <xs:element name="day" type="xs:integer"/>
</xs:schema>

=== YesItIsTrue/repo1/apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_MPA.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///c:/apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_MPA.xsd">
	<TK_test_seq>
		<test_mstr>
			<test_lab_ID>DDI</test_lab_ID>
		</test_mstr>
		<people_mstr>
			<people_lastname>Lincon</people_lastname>
			<people_firstname>Abraham</people_firstname>
			<people_midname>J</people_midname>
			<people_prefname>Ab</people_prefname>
			<people_dob>
				<year>1957</year>
				<month>10</month>
				<day>21</day>
			</people_dob>
			<people_gender>M</people_gender>
			<people_ssn>218688662</people_ssn>
			<people_homephone>510-123-4567</people_homephone>
			<people_workphone>207-787-2000</people_workphone>
		</people_mstr>
		<patient_mstr>
			<patient_notes>Comments - text area</patient_notes>
		</patient_mstr>
		<addr_mstr>
			<addr_addr1>101 Main</addr_addr1>
			<addr_addr2>Apt 201</addr_addr2>
			<addr_city>WALNUT CREEK</addr_city>
			<state_iso>CA</state_iso>
			<addr_zip>94595</addr_zip>
			<country_iso>USA</country_iso>
		</addr_mstr>
		<tk_mstr>
			<TK_ID>MD-123456</TK_ID>
			<tk_lab_sample_ID>B170125-2397-1</tk_lab_sample_ID>
			<tk_test_desc>MPA</tk_test_desc>
			<SNP_ID>rs162036</SNP_ID>
			<SNP_gene>MTRR</SNP_gene>
			<SNP_variation>K350A</SNP_variation>
			<coll_begin>
				<year>2015</year>
				<month>10</month>
				<day>21</day>
			</coll_begin>
		</tk_mstr>
		<tkr_det>
			<set_id>1</set_id>
			<tkr_item>rs10380_call</tkr_item>
			<item-check>rs10380_call</item-check>
			<tkr_lab_ref>+/-</tkr_lab_ref>
			<tkr_lab_results></tkr_lab_results>
			<tkr_lab_ref>-/-</tkr_lab_ref>
		</tkr_det>
		<tkr_det>
			<set_id>2</set_id>
			<tkr_item>rs10380_call</tkr_item>
			<item-check>rs10380_call</item-check>
			<tkr_lab_ref></tkr_lab_ref>
			<tkr_lab_results>Hetero</tkr_lab_results>
			<tkr_lab_ref>-/-</tkr_lab_ref>
		</tkr_det>
		<tk_mstr>
	      <TK_ID>MD-123456</TK_ID>
	      <tk_lab_sample_ID>B170125-2397-1</tk_lab_sample_ID>
	      <tk_test_desc>MPA</tk_test_desc>
	      <SNP_ID>rs819134</SNP_ID>
	      <SNP_gene>AHC Y</SNP_gene>
	      <SNP_variation>2</SNP_variation>
	      <coll_begin>
	        <year>2017</year>
	        <month>01</month>
	        <day>17</day>
	      </coll_begin>
	    </tk_mstr>
		<tkr_det>
	      <set_id>1</set_id>
	      <tkr_item>rs819134</tkr_item>
	      <item-check>rs819134</item-check>
	      <tkr_lab_ref>-/-</tkr_lab_ref>
	    </tkr_det>
	    <tkr_det>
	      <set_id>2</set_id>
	      <tkr_item>rs819134_call</tkr_item>
	      <item-check>rs819134_call</item-check>
	      <tkr_lab_results>T</tkr_lab_results>
	    </tkr_det>
	</TK_test_seq>
</root>
