=== YesItIsTrue/repo1/apps/HL7/bin/xml_schemas/SS_BIOMED.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="TK_test_seq"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TK_test_seq">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="test_mstr"/>
        <xs:element ref="people_mstr"/>
        <xs:element ref="patient_mstr"/>
        <xs:element ref="addr_mstr"/>
        <xs:element ref="tk_mstr" minOccurs="1" maxOccurs="1"/>
        <xs:element maxOccurs="unbounded" ref="tkr_det"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="test_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="test_lab_ID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="test_lab_ID" type="xs:NCName"/>
  <xs:element name="people_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="people_lastname"/>
        <xs:element ref="people_firstname"/>
        <xs:element ref="people_midname"/>
        <xs:element ref="people_prefname" minOccurs="0"/>
        <xs:element ref="people_dob"/>
        <xs:element ref="people_gender" minOccurs="0"/>
        <xs:element ref="people__char1" minOccurs="0"/>
        <xs:element ref="people_homephone" minOccurs="0"/>
        <xs:element ref="people_workphone" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="people_lastname" type="xs:NCName"/>
  <xs:element name="people_firstname" type="xs:NCName"/>
  <xs:element name="people_midname" type="xs:NCName"/>
  <xs:element name="people_prefname" type="xs:NCName"/>
  <xs:element name="people_dob">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="year"/>
        <xs:element ref="month"/>
        <xs:element ref="day"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="people_gender" type="xs:NCName"/>
  <xs:element name="people__char1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SSN" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SSN" type="xs:integer"/>
  <xs:element name="people_homephone" type="xs:NMTOKEN"/>
  <xs:element name="people_workphone" type="xs:NMTOKEN"/>
  <xs:element name="patient_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="patient_notes" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="patient_notes" type="xs:string"/>
  <xs:element name="addr_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="addr_addr1" minOccurs="0"/>
        <xs:element ref="addr_addr2" minOccurs="0"/>
        <xs:element ref="addr_city" minOccurs="0"/>
        <xs:element ref="state_iso" minOccurs="0"/>
        <xs:element ref="addr_zip" minOccurs="0"/>
        <xs:element ref="country_iso" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="addr_addr1" type="xs:string"/>
  <xs:element name="addr_addr2" type="xs:string"/>
  <xs:element name="addr_city" type="xs:string"/>
  <xs:element name="state_iso" type="xs:NCName"/>
  <xs:element name="addr_zip" type="xs:integer"/>
  <xs:element name="country_iso" type="xs:NCName"/>
  <xs:element name="tk_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TK_ID"/>
        <xs:element ref="tk_lab_sample_ID"/>
        <xs:element ref="tk_test_desc"/>
        <xs:element ref="coll_begin" minOccurs="0"/>
        <xs:element ref="coll_end" minOccurs="0"/>
        <xs:element ref="volume" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TK_ID" type="xs:NCName"/>
  <xs:element name="tk_lab_sample_ID" type="xs:NCName"/>
  <xs:element name="tk_test_desc" type="xs:string"/>
  <xs:element name="coll_begin">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="year"/>
        <xs:element ref="month"/>
        <xs:element ref="day"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="coll_end">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="year"/>
        <xs:element ref="month"/>
        <xs:element ref="day"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="volume" type="xs:integer"/>
  <xs:element name="tkr_det">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="set_id"/>
        <xs:element ref="tkr_item"/>
        <xs:element ref="tkr_result"/>
        <xs:element ref="tkr_ref_uom" minOccurs="0"/>
        <xs:element ref="tkr_lab_ref" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="set_id" type="xs:integer"/>
  <xs:element name="tkr_item" type="xs:string"/>
  <xs:element name="tkr_result" type="xs:string"/>
  <xs:element name="tkr_ref_uom" type="xs:string"/>
  <xs:element name="tkr_lab_ref" type="xs:string"/>
  <xs:element name="year" type="xs:integer"/>
  <xs:element name="month" type="xs:integer"/>
  <xs:element name="day" type="xs:integer"/>
</xs:schema>

=== YesItIsTrue/repo1/apps/HL7/Processed/XML/Successful/F140529-2605-1_EDItest-1505215658385.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:///c:/apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_BIOMED.xsd">
   <TK_test_seq>
      <test_mstr>
         <test_lab_ID>DDI</test_lab_ID>
      </test_mstr>
      <people_mstr>
         <people_lastname>Luttrell</people_lastname>
         <people_firstname>Robert</people_firstname>
         <people_midname>J</people_midname>
         <people_prefname>Ab</people_prefname>
         <people_dob>
            <year>1957</year>
            <month>10</month>
            <day>21</day>
         </people_dob>
         <people_gender>M</people_gender>
         <people_ssn>218688662</people_ssn>
         <people_homephone>510-123-4567</people_homephone>
         <people_workphone>207-787-2000</people_workphone>
      </people_mstr>
      <patient_mstr>
         <patient_notes>Comments - text area</patient_notes>
      </patient_mstr>
      <addr_mstr>
         <addr_addr1>101 Main</addr_addr1>
         <addr_addr2>Apt 201</addr_addr2>
         <addr_city>WALNUT CREEK</addr_city>
         <state_iso>CA</state_iso>
         <addr_zip>94595</addr_zip>
         <country_iso>USA</country_iso>
      </addr_mstr>
      <tk_mstr>
         <TK_ID>110B</TK_ID>
         <tk_lab_sample_ID>F170214-2016-1</tk_lab_sample_ID>
         <tk_test_desc>Fecal Metals</tk_test_desc>
         <coll_begin>
            <year>2015</year>
            <month>10</month>
            <day>21</day>
         </coll_begin>
         <coll_end>
            <year>2015</year>
            <month>10</month>
            <day>22</day>
         </coll_end>
         <volume>10</volume>
      </tk_mstr>
      <tkr_det>
         <set_id>2</set_id>
         <tkr_item>F-As</tkr_item>
         <tkr_result>2.53</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.30</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>3</set_id>
         <tkr_item>F-Be</tkr_item>
         <tkr_result>0.011</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.009</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>4</set_id>
         <tkr_item>F-Bi</tkr_item>
         <tkr_result>0.052</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.050</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>5</set_id>
         <tkr_item>F-Cd</tkr_item>
         <tkr_result>0.31</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.50</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>6</set_id>
         <tkr_item>F-Cu</tkr_item>
         <tkr_result>29</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;     60</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>7</set_id>
         <tkr_item>F-Hg1</tkr_item>
         <tkr_result>0.223</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt; 0.05</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>8</set_id>
         <tkr_item>F-Hg2</tkr_item>
         <tkr_result>0.223</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt; 0.5</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>91</set_id>
         <tkr_item>F-Ni</tkr_item>
         <tkr_result>6.1</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;    8.0</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>10</set_id>
         <tkr_item>F-Pb</tkr_item>
         <tkr_result>0.21</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.50</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>11</set_id>
         <tkr_item>F-Pt</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.003</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>12</set_id>
         <tkr_item>F-Sb</tkr_item>
         <tkr_result>0.062</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.080</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>13</set_id>
         <tkr_item>F-Tl</tkr_item>
         <tkr_result>0.024</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.020</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>14</set_id>
         <tkr_item>F-U</tkr_item>
         <tkr_result>0.103</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.120</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>15</set_id>
         <tkr_item>F-W</tkr_item>
         <tkr_result>0.369</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.090</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>16</set_id>
         <tkr_item>WaterContent</tkr_item>
         <tkr_result>66.4</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref>60-85</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>17</set_id>
         <tkr_item>DetoxificationAgent</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>18</set_id>
         <tkr_item>Dosage</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>19</set_id>
         <tkr_item>Provocation</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>20</set_id>
         <tkr_item>DentalAmalgams</tkr_item>
         <tkr_result>not indicated</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>21</set_id>
         <tkr_item>AmalgamQuantity</tkr_item>
         <tkr_result>0</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
   </TK_test_seq>
</root>

=== YesItIsTrue/repo1/apps/HL7/Processed/XML/Successful/F140326-2612-1_EDItest-1505215655605.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:///c:/apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_BIOMED.xsd">
   <TK_test_seq>
      <test_mstr>
         <test_lab_ID>DDI</test_lab_ID>
      </test_mstr>
      <people_mstr>
         <people_lastname>Webber</people_lastname>
         <people_firstname>Matthew</people_firstname>
         <people_midname>S.</people_midname>
         <people_prefname/>
         <people_dob>
            <year>1991</year>
            <month>02</month>
            <day>02</day>
         </people_dob>
         <people_gender>M</people_gender>
         <people_ssn/>
         <people_homephone>207-374-5801</people_homephone>
         <people_workphone/>
      </people_mstr>
      <patient_mstr>
         <patient_notes>Comments - text area</patient_notes>
      </patient_mstr>
      <addr_mstr>
         <addr_addr1>PO Box 391</addr_addr1>
         <addr_addr2>Route 172</addr_addr2>
         <addr_city>Blue Hill</addr_city>
         <state_iso>ME</state_iso>
         <addr_zip>04614</addr_zip>
         <country_iso>USA</country_iso>
      </addr_mstr>
      <tk_mstr>
         <TK_ID>FM-24195</TK_ID>
         <tk_lab_sample_ID>F170214-2016-1</tk_lab_sample_ID>
         <tk_test_desc>Fecal Metals</tk_test_desc>
         <coll_begin>
            <year>2014</year>
            <month>03</month>
            <day>23</day>
         </coll_begin>
         <coll_end>
            <year>2014</year>
            <month>04</month>
            <day>01</day>
         </coll_end>
         <volume/>
      </tk_mstr>
      <tkr_det>
         <set_id>2</set_id>
         <tkr_item>F-As</tkr_item>
         <tkr_result>0.12</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.30</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>3</set_id>
         <tkr_item>F-Be</tkr_item>
         <tkr_result>0.004</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.009</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>4</set_id>
         <tkr_item>F-Bi</tkr_item>
         <tkr_result>120.4</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.050</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>5</set_id>
         <tkr_item>F-Cd</tkr_item>
         <tkr_result>0.14</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.50</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>6</set_id>
         <tkr_item>F-Cu</tkr_item>
         <tkr_result>31</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;     60</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>7</set_id>
         <tkr_item>F-Hg1</tkr_item>
         <tkr_result>0.024</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt; 0.05</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>8</set_id>
         <tkr_item>F-Hg2</tkr_item>
         <tkr_result>0.024</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt; 0.5</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>91</set_id>
         <tkr_item>F-Ni</tkr_item>
         <tkr_result>3.5</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;    8.0</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>10</set_id>
         <tkr_item>F-Pb</tkr_item>
         <tkr_result>0.20</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.50</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>11</set_id>
         <tkr_item>F-Pt</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.003</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>12</set_id>
         <tkr_item>F-Sb</tkr_item>
         <tkr_result>0.076</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.080</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>13</set_id>
         <tkr_item>F-Tl</tkr_item>
         <tkr_result>0.024</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.020</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>14</set_id>
         <tkr_item>F-U</tkr_item>
         <tkr_result>0.643</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.120</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>15</set_id>
         <tkr_item>F-W</tkr_item>
         <tkr_result>0.221</tkr_result>
         <tkr_ref_uom>mg/kg Dry Wt</tkr_ref_uom>
         <tkr_lab_ref>&lt;  0.090</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>16</set_id>
         <tkr_item>WaterContent</tkr_item>
         <tkr_result>74.8</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref>60-85</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>17</set_id>
         <tkr_item>DetoxificationAgent</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>18</set_id>
         <tkr_item>Dosage</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>19</set_id>
         <tkr_item>Provocation</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>20</set_id>
         <tkr_item>DentalAmalgams</tkr_item>
         <tkr_result>not indicated</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>21</set_id>
         <tkr_item>AmalgamQuantity</tkr_item>
         <tkr_result>0</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
   </TK_test_seq>
</root>

=== YesItIsTrue/repo1/apps/HL7/Processed/XML/Successful/U170503-2015-1-EDItest-1505215693953.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:///c:/apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_BIOMED.xsd">
   <TK_test_seq>
      <test_mstr>
         <test_lab_ID>DDI</test_lab_ID>
      </test_mstr>
      <people_mstr>
         <people_lastname>Krashlansky</people_lastname>
         <people_firstname>Leo</people_firstname>
         <people_midname/>
         <people_prefname/>
         <people_dob>
            <year>2006</year>
            <month>08</month>
            <day>07</day>
         </people_dob>
         <people_gender>M</people_gender>
         <people_ssn/>
         <people_homephone/>
         <people_workphone/>
      </people_mstr>
      <patient_mstr>
         <patient_notes/>
      </patient_mstr>
      <addr_mstr>
         <addr_addr1>1959 Blake Ave Unit L</addr_addr1>
         <addr_addr2/>
         <addr_city>LOS ANGELES</addr_city>
         <state_iso>CA</state_iso>
         <addr_zip>90039</addr_zip>
         <country_iso>USA</country_iso>
      </addr_mstr>
      <tk_mstr>
         <TK_ID>UI-69018</TK_ID>
         <tk_lab_sample_ID>U170503-2015-1</tk_lab_sample_ID>
         <tk_test_desc>Neuro-Biogenic Amines, Comprehensive; urine  second morning void</tk_test_desc>
         <coll_begin>
            <year>2017</year>
            <month>04</month>
            <day>30</day>
         </coll_begin>
         <coll_end>
            <year>2017</year>
            <month>05</month>
            <day>01</day>
         </coll_end>
         <volume/>
      </tk_mstr>
      <tkr_det>
         <set_id>1</set_id>
         <tkr_item>Dopamine, free</tkr_item>
         <tkr_result>1230</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>75-   450</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>2</set_id>
         <tkr_item>3,4-Dihydroxyphenylacetic acid (DOPAC)</tkr_item>
         <tkr_result>9673</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>480-  2600</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>3</set_id>
         <tkr_item>3-Methoxytyramine (3-MT)</tkr_item>
         <tkr_result>721</tkr_result>
         <tkr_ref_uom>nmol/g</tkr_ref_uom>
         <tkr_lab_ref>40-   330</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>4</set_id>
         <tkr_item>Norepinephrine, free</tkr_item>
         <tkr_result>25.9</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>20-   104</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>5</set_id>
         <tkr_item>Normetanephrine</tkr_item>
         <tkr_result>196</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>140-   740</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>6</set_id>
         <tkr_item>Epinephrine, free</tkr_item>
         <tkr_result>15</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>1.6-    18</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>7</set_id>
         <tkr_item>Metanephrine</tkr_item>
         <tkr_result>195</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>50-   270</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>8</set_id>
         <tkr_item>Serotonin</tkr_item>
         <tkr_result>121</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>70-   350</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>9</set_id>
         <tkr_item>5-Hydroxyindolacetic acid (5-HIAA)</tkr_item>
         <tkr_result>8452</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>1250- 11000</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>10</set_id>
         <tkr_item>Tryptamine</tkr_item>
         <tkr_result>1.3</tkr_result>
         <tkr_ref_uom>µmol/g</tkr_ref_uom>
         <tkr_lab_ref>0.6-   1.8</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>11</set_id>
         <tkr_item>Glutamate</tkr_item>
         <tkr_result>43</tkr_result>
         <tkr_ref_uom>µmol/g</tkr_ref_uom>
         <tkr_lab_ref>10-    80</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>12</set_id>
         <tkr_item>Gamma-aminobutyrate (GABA)</tkr_item>
         <tkr_result>6.0</tkr_result>
         <tkr_ref_uom>µmol/g</tkr_ref_uom>
         <tkr_lab_ref>1-    10</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>13</set_id>
         <tkr_item>Tyrosine</tkr_item>
         <tkr_result>265</tkr_result>
         <tkr_ref_uom>µmol/g</tkr_ref_uom>
         <tkr_lab_ref>60-   225</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>14</set_id>
         <tkr_item>Tyramine</tkr_item>
         <tkr_result>5.9</tkr_result>
         <tkr_ref_uom>µmol/g</tkr_ref_uom>
         <tkr_lab_ref>2.4-    11</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>15</set_id>
         <tkr_item>Phenethylamine (PEA)</tkr_item>
         <tkr_result>60</tkr_result>
         <tkr_ref_uom>nmol/g</tkr_ref_uom>
         <tkr_lab_ref>21-   200</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>16</set_id>
         <tkr_item>Taurine</tkr_item>
         <tkr_result>3644</tkr_result>
         <tkr_ref_uom>µmol/g</tkr_ref_uom>
         <tkr_lab_ref>200-  1600</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>17</set_id>
         <tkr_item>Glycine</tkr_item>
         <tkr_result>6974</tkr_result>
         <tkr_ref_uom>µmol/g</tkr_ref_uom>
         <tkr_lab_ref>560-  3400</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>18</set_id>
         <tkr_item>Histamine</tkr_item>
         <tkr_result>34</tkr_result>
         <tkr_ref_uom>µg/g</tkr_ref_uom>
         <tkr_lab_ref>8-    80</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>19</set_id>
         <tkr_item>U-CREAT</tkr_item>
         <tkr_result>16</tkr_result>
         <tkr_ref_uom>mg/dL</tkr_ref_uom>
         <tkr_lab_ref>25-   180</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>20</set_id>
         <tkr_item>U-Vol 24hr</tkr_item>
         <tkr_result/>
         <tkr_ref_uom>mL</tkr_ref_uom>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>21</set_id>
         <tkr_item>Time Collected</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>22</set_id>
         <tkr_item>Col Period</tkr_item>
         <tkr_result> second morning void</tkr_result>
         <tkr_ref_uom>Hours</tkr_ref_uom>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>23</set_id>
         <tkr_item>Body Surface Area</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
   </TK_test_seq>
</root>
