=== YesItIsTrue/repo1/apps/HL7/bin/xml_schemas/SS_BIOMED.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="TK_test_seq"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TK_test_seq">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="test_mstr"/>
        <xs:element ref="people_mstr"/>
        <xs:element ref="patient_mstr"/>
        <xs:element ref="addr_mstr"/>
        <xs:element ref="tk_mstr" minOccurs="1" maxOccurs="1"/>
        <xs:element maxOccurs="unbounded" ref="tkr_det"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="test_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="test_lab_ID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="test_lab_ID" type="xs:NCName"/>
  <xs:element name="people_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="people_lastname"/>
        <xs:element ref="people_firstname"/>
        <xs:element ref="people_midname"/>
        <xs:element ref="people_prefname" minOccurs="0"/>
        <xs:element ref="people_dob"/>
        <xs:element ref="people_gender" minOccurs="0"/>
        <xs:element ref="people__char1" minOccurs="0"/>
        <xs:element ref="people_homephone" minOccurs="0"/>
        <xs:element ref="people_workphone" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="people_lastname" type="xs:NCName"/>
  <xs:element name="people_firstname" type="xs:NCName"/>
  <xs:element name="people_midname" type="xs:NCName"/>
  <xs:element name="people_prefname" type="xs:NCName"/>
  <xs:element name="people_dob">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="year"/>
        <xs:element ref="month"/>
        <xs:element ref="day"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="people_gender" type="xs:NCName"/>
  <xs:element name="people__char1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SSN" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SSN" type="xs:integer"/>
  <xs:element name="people_homephone" type="xs:NMTOKEN"/>
  <xs:element name="people_workphone" type="xs:NMTOKEN"/>
  <xs:element name="patient_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="patient_notes" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="patient_notes" type="xs:string"/>
  <xs:element name="addr_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="addr_addr1" minOccurs="0"/>
        <xs:element ref="addr_addr2" minOccurs="0"/>
        <xs:element ref="addr_city" minOccurs="0"/>
        <xs:element ref="state_iso" minOccurs="0"/>
        <xs:element ref="addr_zip" minOccurs="0"/>
        <xs:element ref="country_iso" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="addr_addr1" type="xs:string"/>
  <xs:element name="addr_addr2" type="xs:string"/>
  <xs:element name="addr_city" type="xs:string"/>
  <xs:element name="state_iso" type="xs:NCName"/>
  <xs:element name="addr_zip" type="xs:integer"/>
  <xs:element name="country_iso" type="xs:NCName"/>
  <xs:element name="tk_mstr">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TK_ID"/>
        <xs:element ref="tk_lab_sample_ID"/>
        <xs:element ref="tk_test_desc"/>
        <xs:element ref="coll_begin" minOccurs="0"/>
        <xs:element ref="coll_end" minOccurs="0"/>
        <xs:element ref="volume" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TK_ID" type="xs:NCName"/>
  <xs:element name="tk_lab_sample_ID" type="xs:NCName"/>
  <xs:element name="tk_test_desc" type="xs:string"/>
  <xs:element name="coll_begin">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="year"/>
        <xs:element ref="month"/>
        <xs:element ref="day"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="coll_end">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="year"/>
        <xs:element ref="month"/>
        <xs:element ref="day"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="volume" type="xs:integer"/>
  <xs:element name="tkr_det">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="set_id"/>
        <xs:element ref="tkr_item"/>
        <xs:element ref="tkr_result"/>
        <xs:element ref="tkr_ref_uom" minOccurs="0"/>
        <xs:element ref="tkr_lab_ref" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="set_id" type="xs:integer"/>
  <xs:element name="tkr_item" type="xs:string"/>
  <xs:element name="tkr_result" type="xs:string"/>
  <xs:element name="tkr_ref_uom" type="xs:string"/>
  <xs:element name="tkr_lab_ref" type="xs:string"/>
  <xs:element name="year" type="xs:integer"/>
  <xs:element name="month" type="xs:integer"/>
  <xs:element name="day" type="xs:integer"/>
</xs:schema>

=== YesItIsTrue/repo1/apps/HL7/Processed/XML/Successful/U170224-2135-1_EDItest-1505215688724.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:///c:/apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_BIOMED.xsd">
   <TK_test_seq>
      <test_mstr>
         <test_lab_ID>DDI</test_lab_ID>
      </test_mstr>
      <people_mstr>
         <people_lastname>Lal</people_lastname>
         <people_firstname>Sahib</people_firstname>
         <people_midname/>
         <people_prefname/>
         <people_dob>
            <year>2008</year>
            <month>08</month>
            <day>03</day>
         </people_dob>
         <people_gender>M</people_gender>
         <people_ssn/>
         <people_homephone/>
         <people_workphone/>
      </people_mstr>
      <patient_mstr>
         <patient_notes/>
      </patient_mstr>
      <addr_mstr>
         <addr_addr1/>
         <addr_addr2/>
         <addr_city/>
         <state_iso/>
         <addr_zip/>
         <country_iso/>
      </addr_mstr>
      <tk_mstr>
         <TK_ID>UP-39029</TK_ID>
         <tk_lab_sample_ID>U170224-2135-1</tk_lab_sample_ID>
         <tk_test_desc>Urine Porphyrins</tk_test_desc>
         <coll_begin>
            <year>2017</year>
            <month>02</month>
            <day>22</day>
         </coll_begin>
         <coll_end>
            <year>2017</year>
            <month>03</month>
            <day>01</day>
         </coll_end>
         <volume/>
      </tk_mstr>
      <tkr_det>
         <set_id>2</set_id>
         <tkr_item>Uroporphyrins/Creat</tkr_item>
         <tkr_result>220</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;     30</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>3</set_id>
         <tkr_item>Heptacarboxylporphyrins/Creat</tkr_item>
         <tkr_result>3.9</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      6</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>4</set_id>
         <tkr_item>Hexacarboyxlporphyrins/Creat</tkr_item>
         <tkr_result>0.6</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    5.2</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>5</set_id>
         <tkr_item>Pentacarboxylporphyrins/Creat</tkr_item>
         <tkr_result>1.2</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    4.5</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>6</set_id>
         <tkr_item>CoproporphyrinI/Creat</tkr_item>
         <tkr_result>29</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;     36</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>7</set_id>
         <tkr_item>CoproporphyrinIII/Creat</tkr_item>
         <tkr_result>130</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    105</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>8</set_id>
         <tkr_item>CoproI_CoproIII_ratio/Creat</tkr_item>
         <tkr_result>0.21</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    0.8</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>9</set_id>
         <tkr_item>Total_Porphyrins/Creat</tkr_item>
         <tkr_result>390</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    160</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>10</set_id>
         <tkr_item>PrecoproporphyrinI/Creat</tkr_item>
         <tkr_result>2.1</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      2</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>11</set_id>
         <tkr_item>PrecoproporphyrinII/Creat</tkr_item>
         <tkr_result>1</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    1.2</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>12</set_id>
         <tkr_item>PrecoproporphyrinIII/Creat</tkr_item>
         <tkr_result>0</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    1.2</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>13</set_id>
         <tkr_item>Total_Precoproporphyrins/Creat</tkr_item>
         <tkr_result>3.1</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      4</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>14</set_id>
         <tkr_item>Precopro/Uroporph_ratio/Creat</tkr_item>
         <tkr_result>0.014</tkr_result>
         <tkr_ref_uom>nmol/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    0.1</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>22</set_id>
         <tkr_item>Creatinine-CREAT</tkr_item>
         <tkr_result>137</tkr_result>
         <tkr_ref_uom>mg/dL</tkr_ref_uom>
         <tkr_lab_ref>25-   180</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>23</set_id>
         <tkr_item>U-Vol 24hr</tkr_item>
         <tkr_result/>
         <tkr_ref_uom>mL</tkr_ref_uom>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>24</set_id>
         <tkr_item>Col Period</tkr_item>
         <tkr_result>Random</tkr_result>
         <tkr_ref_uom>Hours</tkr_ref_uom>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>25</set_id>
         <tkr_item>Provocation</tkr_item>
         <tkr_result/>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
   </TK_test_seq>
</root>

=== YesItIsTrue/repo1/apps/HL7/Processed/XML/Successful/U170410-2191-1EDItest-1505215691110.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:///c:/apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_BIOMED.xsd">
   <TK_test_seq>
      <test_mstr>
         <test_lab_ID>DDI</test_lab_ID>
      </test_mstr>
      <people_mstr>
         <people_lastname>Hamilton</people_lastname>
         <people_firstname>Jonas</people_firstname>
         <people_midname/>
         <people_prefname/>
         <people_dob>
            <year>1996</year>
            <month>05</month>
            <day>27</day>
         </people_dob>
         <people_gender>M</people_gender>
         <people_ssn>009803949</people_ssn>
         <people_homephone>802-492-3792</people_homephone>
         <people_workphone/>
      </people_mstr>
      <patient_mstr>
         <patient_notes/>
      </patient_mstr>
      <addr_mstr>
         <addr_addr1>63 Copperas Hill Rd</addr_addr1>
         <addr_addr2/>
         <addr_city>SHREWSBURY</addr_city>
         <state_iso>VT</state_iso>
         <addr_zip>05738</addr_zip>
         <country_iso>USA</country_iso>
      </addr_mstr>
      <tk_mstr>
         <TK_ID>NC-69029</TK_ID>
         <tk_lab_sample_ID>U170410-2191-1</tk_lab_sample_ID>
         <tk_test_desc>Neuro-Biogenic Amines, Comprehensive; urine  first morning void</tk_test_desc>
         <coll_begin>
            <year>2017</year>
            <month>04</month>
            <day>05</day>
         </coll_begin>
         <coll_end>
            <year>2017</year>
            <month>04</month>
            <day>06</day>
         </coll_end>
         <volume/>
      </tk_mstr>
      <tkr_det>
         <set_id>1</set_id>
         <tkr_item>Dopamine, free</tkr_item>
         <tkr_result>181</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>52-   320</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>2</set_id>
         <tkr_item>3,4-Dihydroxyphenylacetic acid (DOPAC)</tkr_item>
         <tkr_result>1421</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>360-  1950</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>3</set_id>
         <tkr_item>3-Methoxytyramine (3-MT)</tkr_item>
         <tkr_result>155</tkr_result>
         <tkr_ref_uom>nmol</tkr_ref_uom>
         <tkr_lab_ref>25-   200</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>4</set_id>
         <tkr_item>Norepinephrine, free</tkr_item>
         <tkr_result>21.1</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>12-    64</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>5</set_id>
         <tkr_item>Normetanephrine</tkr_item>
         <tkr_result>170</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>64-   400</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>6</set_id>
         <tkr_item>Epinephrine, free</tkr_item>
         <tkr_result>7.8</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>1.2-    16</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>7</set_id>
         <tkr_item>Metanephrine</tkr_item>
         <tkr_result>155</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>35-   200</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>8</set_id>
         <tkr_item>Serotonin</tkr_item>
         <tkr_result>65.3</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>40-   200</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>9</set_id>
         <tkr_item>5-Hydroxyindolacetic acid (5-HIAA)</tkr_item>
         <tkr_result>2208</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>800-  7200</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>10</set_id>
         <tkr_item>Tryptamine</tkr_item>
         <tkr_result>0.20</tkr_result>
         <tkr_ref_uom>µmol</tkr_ref_uom>
         <tkr_lab_ref>0.15-   1.1</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>11</set_id>
         <tkr_item>Glutamate</tkr_item>
         <tkr_result>17</tkr_result>
         <tkr_ref_uom>µmol</tkr_ref_uom>
         <tkr_lab_ref>5-    45</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>12</set_id>
         <tkr_item>Gamma-aminobutyrate (GABA)</tkr_item>
         <tkr_result>3.3</tkr_result>
         <tkr_ref_uom>µmol</tkr_ref_uom>
         <tkr_lab_ref>1-   6.5</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>13</set_id>
         <tkr_item>Tyrosine</tkr_item>
         <tkr_result>27</tkr_result>
         <tkr_ref_uom>µmol</tkr_ref_uom>
         <tkr_lab_ref>23-   113</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>14</set_id>
         <tkr_item>Tyramine</tkr_item>
         <tkr_result>1.6</tkr_result>
         <tkr_ref_uom>µmol</tkr_ref_uom>
         <tkr_lab_ref>1.2-   5.5</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>15</set_id>
         <tkr_item>Phenethylamine (PEA)</tkr_item>
         <tkr_result>20</tkr_result>
         <tkr_ref_uom>nmol</tkr_ref_uom>
         <tkr_lab_ref>13-   130</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>16</set_id>
         <tkr_item>Taurine</tkr_item>
         <tkr_result>514</tkr_result>
         <tkr_ref_uom>µmol</tkr_ref_uom>
         <tkr_lab_ref>170-  1200</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>17</set_id>
         <tkr_item>Glycine</tkr_item>
         <tkr_result>532</tkr_result>
         <tkr_ref_uom>µmol</tkr_ref_uom>
         <tkr_lab_ref>280-  2800</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>18</set_id>
         <tkr_item>Histamine</tkr_item>
         <tkr_result>19</tkr_result>
         <tkr_ref_uom>µg</tkr_ref_uom>
         <tkr_lab_ref>5-    48</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>19</set_id>
         <tkr_item>U-CREAT</tkr_item>
         <tkr_result>89</tkr_result>
         <tkr_ref_uom>mg/dL</tkr_ref_uom>
         <tkr_lab_ref>35-   240</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>20</set_id>
         <tkr_item>U-Vol 24hr</tkr_item>
         <tkr_result/>
         <tkr_ref_uom>mL</tkr_ref_uom>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>21</set_id>
         <tkr_item>Time Collected</tkr_item>
         <tkr_result>12:30 PM</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>22</set_id>
         <tkr_item>Col Period</tkr_item>
         <tkr_result> first morning void</tkr_result>
         <tkr_ref_uom>Hours</tkr_ref_uom>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>23</set_id>
         <tkr_item>Body Surface Area</tkr_item>
         <tkr_result>2.03</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
   </TK_test_seq>
</root>

=== YesItIsTrue/repo1/HL7/bin/SS_XML_Files/DONT_TOUCH/SS_BIOMED.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SS_BIOMED.xsd">
	<TK_test_seq>
		<test_mstr>
			<test_lab_ID>DDI</test_lab_ID>
		</test_mstr>
		<people_mstr>
			<people_lastname>Lincon</people_lastname>
			<people_firstname>Abraham</people_firstname>
			<people_midname>J</people_midname>
			<people_prefname>Ab</people_prefname>
			<people_dob>
				<year>1957</year>
				<month>10</month>
				<day>21</day>
			</people_dob>
			<people_gender>M</people_gender>
			<people_ssn>218688662</people_ssn>
			<people_homephone>510-123-4567</people_homephone>
			<people_workphone>207-787-2000</people_workphone>
		</people_mstr>
		<patient_mstr>
			<patient_notes>Comments - text area</patient_notes>
		</patient_mstr>
		<addr_mstr>
			<addr_addr1>101 Main</addr_addr1>
			<addr_addr2>Apt 201</addr_addr2>
			<addr_city>WALNUT CREEK</addr_city>
			<state_iso>CA</state_iso>
			<addr_zip>94595</addr_zip>
			<country_iso>USA</country_iso>
		</addr_mstr>
		<tk_mstr>
			<TK_ID>UTM-123456</TK_ID>
			<tk_lab_sample_ID>U170125-2073-1</tk_lab_sample_ID>
			<tk_test_desc>Urine Toxic Metals</tk_test_desc>
			<coll_begin>
				<year>2015</year>
				<month>10</month>
				<day>21</day>
			</coll_begin>
			<coll_end>
				<year>2015</year>
				<month>10</month>
				<day>22</day>
			</coll_end>
			<volume>10</volume>
		</tk_mstr>
		<tkr_det>
			<set_id>1</set_id>
			<tkr_item>U-As/Creat</tkr_item>
			<tkr_result>&lt; dl</tkr_result>
			<tkr_ref_uom>ug/g Creat</tkr_ref_uom>
			<tkr_lab_ref>&lt; 1</tkr_lab_ref>
		</tkr_det>
	</TK_test_seq>
	<TK_test_seq>
		<test_mstr>
			<test_lab_ID>DDI</test_lab_ID>
		</test_mstr>
		<people_mstr>
			<people_lastname>Lincon</people_lastname>
			<people_firstname>Abraham</people_firstname>
			<people_midname>J</people_midname>
			<people_prefname>Ab</people_prefname>
			<people_dob>
				<year>1957</year>
				<month>10</month>
				<day>21</day>
			</people_dob>
			<people_gender>M</people_gender>
			<people_ssn>218688662</people_ssn>
			<people_homephone>510-123-4567</people_homephone>
			<people_workphone>207-787-2000</people_workphone>
		</people_mstr>
		<patient_mstr>
			<patient_notes>Comments - text area</patient_notes>
		</patient_mstr>
		<addr_mstr>
			<addr_addr1>101 Main</addr_addr1>
			<addr_addr2>Apt 201</addr_addr2>
			<addr_city>WALNUT CREEK</addr_city>
			<state_iso>CA</state_iso>
			<addr_zip>94595</addr_zip>
			<country_iso>USA</country_iso>
		</addr_mstr>
		<tk_mstr>
			<TK_ID>UTM-123456</TK_ID>
			<tk_lab_sample_ID>U170125-2073-1</tk_lab_sample_ID>
			<tk_test_desc>Urine Toxic Metals</tk_test_desc>
			<coll_begin>
				<year>2015</year>
				<month>10</month>
				<day>21</day>
			</coll_begin>
			<coll_end>
				<year>2015</year>
				<month>10</month>
				<day>22</day>
			</coll_end>
			<volume>10</volume>
		</tk_mstr>
		<tkr_det>
			<set_id>1</set_id>
			<tkr_item>U-As/Creat</tkr_item>
			<tkr_result>&lt; dl</tkr_result>
			<tkr_ref_uom>ug/g Creat</tkr_ref_uom>
			<tkr_lab_ref>&lt; 1</tkr_lab_ref>
		</tkr_det>
	</TK_test_seq>
</root>

=== YesItIsTrue/repo1/apps/HL7/Processed/XML/Successful/U150624-2073-1_EDItest-1505215683283.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:///c:/apps/HL7/src/SS_XML_Files/DONT_TOUCH/SS_BIOMED.xsd">
   <TK_test_seq>
      <test_mstr>
         <test_lab_ID>DDI</test_lab_ID>
      </test_mstr>
      <people_mstr>
         <people_lastname>Webber</people_lastname>
         <people_firstname>Matthew</people_firstname>
         <people_midname>S.</people_midname>
         <people_prefname/>
         <people_dob>
            <year>1991</year>
            <month>02</month>
            <day>02</day>
         </people_dob>
         <people_gender>M</people_gender>
         <people_ssn/>
         <people_homephone>207-374-5801</people_homephone>
         <people_workphone/>
      </people_mstr>
      <patient_mstr>
         <patient_notes>Comments - text area</patient_notes>
      </patient_mstr>
      <addr_mstr>
         <addr_addr1>PO Box 391</addr_addr1>
         <addr_addr2>Route 172</addr_addr2>
         <addr_city>Blue Hill</addr_city>
         <state_iso>ME</state_iso>
         <addr_zip>04614</addr_zip>
         <country_iso>USA</country_iso>
      </addr_mstr>
      <tk_mstr>
         <TK_ID>UTM-29142</TK_ID>
         <tk_lab_sample_ID>U150624-2073-1</tk_lab_sample_ID>
         <tk_test_desc>Urine Toxic Metals</tk_test_desc>
         <coll_begin>
            <year>2015</year>
            <month>06</month>
            <day>21</day>
         </coll_begin>
         <coll_end>
            <year>2015</year>
            <month>06</month>
            <day>25</day>
         </coll_end>
         <volume>10</volume>
      </tk_mstr>
      <tkr_det>
         <set_id>2</set_id>
         <tkr_item>U-Al/Creat</tkr_item>
         <tkr_result>7.6</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;     25</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>3</set_id>
         <tkr_item>U-As/Creat</tkr_item>
         <tkr_result>10</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;     75</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>4</set_id>
         <tkr_item>U-Ba/Creat</tkr_item>
         <tkr_result>2.5</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      7</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>5</set_id>
         <tkr_item>U-Be/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      1</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>6</set_id>
         <tkr_item>U-Bi/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      2</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>7</set_id>
         <tkr_item>U-Cd/Creat</tkr_item>
         <tkr_result>0.2</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      0.8</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>8</set_id>
         <tkr_item>U-Cs/Creat</tkr_item>
         <tkr_result>6.2</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;     8</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>9</set_id>
         <tkr_item>U-Gd/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    0.5</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>10</set_id>
         <tkr_item>U-Hg/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      3</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>11</set_id>
         <tkr_item>U-Ni/Creat</tkr_item>
         <tkr_result>6.7</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;     6.7</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>12</set_id>
         <tkr_item>U-Pb/Creat</tkr_item>
         <tkr_result>0.2</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      2</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>13</set_id>
         <tkr_item>U-Pd/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.1</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>14</set_id>
         <tkr_item>U-Pt/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    0.1</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>15</set_id>
         <tkr_item>U-Sb/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    0.2</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>16</set_id>
         <tkr_item>U-Sn/Creat</tkr_item>
         <tkr_result>2.5</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;      4</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>17</set_id>
         <tkr_item>U-Te/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    0.5</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>18</set_id>
         <tkr_item>U-Th/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.03</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>19</set_id>
         <tkr_item>U-Tl/Creat</tkr_item>
         <tkr_result>0.3</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    0.5</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>20</set_id>
         <tkr_item>U-U/Creat</tkr_item>
         <tkr_result>&lt; dl</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;   0.03</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>21</set_id>
         <tkr_item>U-W/Creat</tkr_item>
         <tkr_result>0.03</tkr_result>
         <tkr_ref_uom>µg/g Creat</tkr_ref_uom>
         <tkr_lab_ref>&lt;    0.4</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>22</set_id>
         <tkr_item>U-CREAT</tkr_item>
         <tkr_result>83.1</tkr_result>
         <tkr_ref_uom>mg/dL</tkr_ref_uom>
         <tkr_lab_ref>35-   240</tkr_lab_ref>
      </tkr_det>
      <tkr_det>
         <set_id>23</set_id>
         <tkr_item>U-Vol 24hr</tkr_item>
         <tkr_result/>
         <tkr_ref_uom>mL</tkr_ref_uom>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>24</set_id>
         <tkr_item>Col Period</tkr_item>
         <tkr_result>timed: 6 hours</tkr_result>
         <tkr_ref_uom>Hours</tkr_ref_uom>
         <tkr_lab_ref/>
      </tkr_det>
      <tkr_det>
         <set_id>25</set_id>
         <tkr_item>Provocation</tkr_item>
         <tkr_result>POST PROVOCATIVE</tkr_result>
         <tkr_ref_uom/>
         <tkr_lab_ref/>
      </tkr_det>
   </TK_test_seq>
</root>
