=== YesItIsTrue/repo1/HL7/src/HL7_XML_Files/DONT_TOUCH/HL7_MPA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="HL7">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ORU_R01"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ORU_R01">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MSH"/>
        <xs:element ref="PID"/>
        <xs:element ref="PV1"/>
        <xs:element ref="ORC"/>
        <xs:element ref="NTE"/>
        <xs:element ref="ZCF"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="OBR"/>
          <xs:element ref="OBX"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MSH">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MSH.1"/>
        <xs:element ref="MSH.2"/>
        <xs:element ref="MSH.3"/>
        <xs:element ref="MSH.4"/>
        <xs:element ref="MSH.5"/>
        <xs:element ref="MSH.6"/>
        <xs:element ref="MSH.7"/>
        <xs:element ref="MSH.9"/>
        <xs:element ref="MSH.11"/>
        <xs:element ref="MSH.12"/>
        <xs:element ref="MSH.15"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MSH.1" type="xs:string"/>
  <xs:element name="MSH.2" type="xs:string"/>
  <xs:element name="MSH.3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MSH.3.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MSH.3.1" type="xs:NCName"/>
  <xs:element name="MSH.4">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MSH.4.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MSH.4.1" type="xs:NCName"/>
  <xs:element name="MSH.5">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MSH.5.1"/>
        <xs:element ref="MSH.5.2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MSH.5.1" type="xs:string"/>
  <xs:element name="MSH.5.2" type="xs:NCName"/>
  <xs:element name="MSH.6">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MSH.6.1"/>
        <xs:element ref="MSH.6.2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MSH.6.1" type="xs:string"/>
  <xs:element name="MSH.6.2" type="xs:NCName"/>
  <xs:element name="MSH.7" type="xs:integer"/>
  <xs:element name="MSH.9">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MSH.9.1"/>
        <xs:element ref="MSH.9.2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MSH.9.1" type="xs:NCName"/>
  <xs:element name="MSH.9.2" type="xs:NCName"/>
  <xs:element name="MSH.11">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MSH.11.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="MSH.11.1" type="xs:NCName"/>
  <xs:element name="MSH.12" type="xs:decimal"/>
  <xs:element name="MSH.15" type="xs:NCName"/>
  <xs:element name="PID">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.1"/>
        <xs:element ref="PID.3"/>
        <xs:element ref="PID.5"/>
        <xs:element ref="PID.7"/>
        <xs:element ref="PID.8"/>
        <xs:element ref="PID.9"/>
        <xs:element ref="PID.11"/>
        <xs:element ref="PID.12"/>
        <xs:element ref="PID.13"/>
        <xs:element ref="PID.14"/>
        <xs:element ref="PID.19"/>
        <xs:element ref="PID.30"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.1" type="xs:integer"/>
  <xs:element name="PID.3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.3.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.3.1" type="xs:NCName"/>
  <xs:element name="PID.5">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.5.1"/>
        <xs:element ref="PID.5.2"/>
        <xs:element ref="PID.5.3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.5.1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.5.1.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.5.1.1" type="xs:NCName"/>
  <xs:element name="PID.5.2" type="xs:NCName"/>
  <xs:element name="PID.5.3" type="xs:NCName"/>
  <xs:element name="PID.7" type="xs:integer"/>
  <xs:element name="PID.8" type="xs:NCName"/>
  <xs:element name="PID.9">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.9.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.9.1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.9.1.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.9.1.1" type="xs:NCName"/>
  <xs:element name="PID.11">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.11.1"/>
        <xs:element ref="PID.11.2"/>
        <xs:element ref="PID.11.3"/>
        <xs:element ref="PID.11.4"/>
        <xs:element ref="PID.11.5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.11.1" type="xs:string"/>
  <xs:element name="PID.11.2" type="xs:string"/>
  <xs:element name="PID.11.3" type="xs:string"/>
  <xs:element name="PID.11.4" type="xs:NCName"/>
  <xs:element name="PID.11.5" type="xs:integer"/>
  <xs:element name="PID.12" type="xs:NCName"/>
  <xs:element name="PID.13">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.13.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.13.1" type="xs:NMTOKEN"/>
  <xs:element name="PID.14">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PID.14.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PID.14.1" type="xs:NMTOKEN"/>
  <xs:element name="PID.19" type="xs:integer"/>
  <xs:element name="PID.30" type="xs:NCName"/>
  <xs:element name="PV1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PV1.1"/>
        <xs:element ref="PV1.3"/>
        <xs:element ref="PV1.7"/>
        <xs:element ref="PV1.19"/>
        <xs:element ref="PV1.50"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PV1.1" type="xs:integer"/>
  <xs:element name="PV1.3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PV1.3.4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PV1.3.4">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PV1.3.4.1"/>
        <xs:element ref="PV1.3.4.2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PV1.3.4.1" type="xs:NCName"/>
  <xs:element name="PV1.3.4.2" type="xs:integer"/>
  <xs:element name="PV1.7">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PV1.7.2"/>
        <xs:element ref="PV1.7.3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PV1.7.2">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PV1.7.2.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PV1.7.2.1" type="xs:NCName"/>
  <xs:element name="PV1.7.3" type="xs:NCName"/>
  <xs:element name="PV1.19">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PV1.19.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PV1.19.1" type="xs:NCName"/>
  <xs:element name="PV1.50">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PV1.50.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PV1.50.1" type="xs:NMTOKEN"/>
  <xs:element name="ORC">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ORC.1"/>
        <xs:element ref="ORC.3"/>
        <xs:element ref="ORC.4"/>
        <xs:element ref="ORC.7"/>
        <xs:element ref="ORC.12"/>
        <xs:element ref="ORC.13"/>
        <xs:element ref="ORC.20"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ORC.1" type="xs:NCName"/>
  <xs:element name="ORC.3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ORC.3.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ORC.3.1" type="xs:NCName"/>
  <xs:element name="ORC.4">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ORC.4.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ORC.4.1" type="xs:integer"/>
  <xs:element name="ORC.7">
    <xs:complexType/>
  </xs:element>
  <xs:element name="ORC.12">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ORC.12.2"/>
        <xs:element ref="ORC.12.3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ORC.12.2">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ORC.12.2.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ORC.12.2.1" type="xs:NCName"/>
  <xs:element name="ORC.12.3" type="xs:NCName"/>
  <xs:element name="ORC.13">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ORC.13.4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ORC.13.4">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ORC.13.4.1"/>
        <xs:element ref="ORC.13.4.2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ORC.13.4.1" type="xs:NCName"/>
  <xs:element name="ORC.13.4.2" type="xs:integer"/>
  <xs:element name="ORC.20" type="xs:integer"/>
  <xs:element name="NTE">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="NTE.1"/>
        <xs:element ref="NTE.3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="NTE.1" type="xs:integer"/>
  <xs:element name="NTE.3" type="xs:string"/>
  <xs:element name="ZCF">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ZCF.1"/>
        <xs:element ref="ZCF.3"/>
        <xs:element ref="ZCF.5"/>
        <xs:element ref="ZCF.7"/>
        <xs:element ref="ZCF.9"/>
        <xs:element ref="ZCF.10"/>
        <xs:element ref="ZCF.11"/>
        <xs:element ref="ZCF.12"/>
        <xs:element ref="ZCF.13"/>
        <xs:element ref="ZCF.14"/>
        <xs:element ref="ZCF.15"/>
        <xs:element ref="ZCF.16"/>
        <xs:element ref="ZCF.17"/>
        <xs:element ref="ZCF.18"/>
        <xs:element ref="ZCF.19"/>
        <xs:element ref="ZCF.20"/>
        <xs:element ref="ZCF.21"/>
        <xs:element ref="ZCF.22"/>
        <xs:element ref="ZCF.23"/>
        <xs:element ref="ZCF.24"/>
        <xs:element ref="ZCF.25"/>
        <xs:element ref="ZCF.26"/>
        <xs:element ref="ZCF.27"/>
        <xs:element ref="ZCF.28"/>
        <xs:element ref="ZCF.29"/>
        <xs:element ref="ZCF.31"/>
        <xs:element ref="ZCF.33"/>
        <xs:element ref="ZCF.35"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ZCF.1" type="xs:string"/>
  <xs:element name="ZCF.3" type="xs:string"/>
  <xs:element name="ZCF.5" type="xs:string"/>
  <xs:element name="ZCF.7" type="xs:NMTOKEN"/>
  <xs:element name="ZCF.9" type="xs:string"/>
  <xs:element name="ZCF.10" type="xs:string"/>
  <xs:element name="ZCF.11" type="xs:string"/>
  <xs:element name="ZCF.12" type="xs:string"/>
  <xs:element name="ZCF.13" type="xs:NMTOKEN"/>
  <xs:element name="ZCF.14" type="xs:integer"/>
  <xs:element name="ZCF.15" type="xs:NMTOKEN"/>
  <xs:element name="ZCF.16" type="xs:integer"/>
  <xs:element name="ZCF.17" type="xs:string"/>
  <xs:element name="ZCF.18" type="xs:NCName"/>
  <xs:element name="ZCF.19" type="xs:NMTOKEN"/>
  <xs:element name="ZCF.20" type="xs:string"/>
  <xs:element name="ZCF.21" type="xs:NMTOKEN"/>
  <xs:element name="ZCF.22" type="xs:NCName"/>
  <xs:element name="ZCF.23" type="xs:NMTOKEN"/>
  <xs:element name="ZCF.24" type="xs:NCName"/>
  <xs:element name="ZCF.25" type="xs:NMTOKEN"/>
  <xs:element name="ZCF.26" type="xs:integer"/>
  <xs:element name="ZCF.27" type="xs:string"/>
  <xs:element name="ZCF.28" type="xs:NCName"/>
  <xs:element name="ZCF.29" type="xs:string"/>
  <xs:element name="ZCF.31" type="xs:string"/>
  <xs:element name="ZCF.33" type="xs:string"/>
  <xs:element name="ZCF.35" type="xs:string"/>
  <xs:element name="OBR">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.1"/>
        <xs:element ref="OBR.3"/>
        <xs:element ref="OBR.4"/>
        <xs:element ref="OBR.5"/>
        <xs:element ref="OBR.7"/>
        <xs:element minOccurs="0" ref="OBR.10"/>
        <xs:element ref="OBR.15"/>
        <xs:element ref="OBR.16"/>
        <xs:element ref="OBR.24"/>
        <xs:element minOccurs="0" ref="OBR.25"/>
        <xs:element ref="OBR.27"/>
        <xs:element ref="OBR.29"/>
        <xs:element ref="OBR.30"/>
        <xs:choice>
          <xs:element ref="OBR.51"/>
          <xs:element ref="OBR.55"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.1" type="xs:integer"/>
  <xs:element name="OBR.3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.3.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.3.1" type="xs:NCName"/>
  <xs:element name="OBR.4">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.4.1"/>
        <xs:element ref="OBR.4.2"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.4.1" type="xs:NCName"/>
  <xs:element name="OBR.4.2" type="xs:string"/>
  <xs:element name="OBR.5" type="xs:NCName"/>
  <xs:element name="OBR.7" type="xs:integer"/>
  <xs:element name="OBR.10">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.10.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.10.1" type="xs:NCName"/>
  <xs:element name="OBR.15">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.15.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.15.1" type="xs:NCName"/>
  <xs:element name="OBR.16">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.16.2"/>
        <xs:element ref="OBR.16.3"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.16.2">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.16.2.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.16.2.1" type="xs:NCName"/>
  <xs:element name="OBR.16.3" type="xs:NCName"/>
  <xs:element name="OBR.24" type="xs:NCName"/>
  <xs:element name="OBR.25" type="xs:NCName"/>
  <xs:element name="OBR.27">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.27.6"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.27.6" type="xs:NCName"/>
  <xs:element name="OBR.29">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBR.29.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBR.29.1" type="xs:NMTOKEN"/>
  <xs:element name="OBR.30" type="xs:NCName"/>
  <xs:element name="OBR.51" type="xs:NCName"/>
  <xs:element name="OBR.55" type="xs:NCName"/>
  <xs:element name="OBX">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBX.1"/>
        <xs:element ref="OBX.2"/>
        <xs:element ref="OBX.3"/>
        <xs:element ref="OBX.5"/>
        <xs:element minOccurs="0" ref="OBX.7"/>
        <xs:element ref="OBX.11"/>
        <xs:element ref="OBX.14"/>
        <xs:element ref="OBX.15"/>
        <xs:element ref="OBX.16"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBX.1" type="xs:integer"/>
  <xs:element name="OBX.2" type="xs:NCName"/>
  <xs:element name="OBX.3">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBX.3.1"/>
        <xs:element ref="OBX.3.2"/>
        <xs:element ref="OBX.3.3"/>
        <xs:element ref="OBX.3.6"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBX.3.1" type="xs:NCName"/>
  <xs:element name="OBX.3.2" type="xs:NCName"/>
  <xs:element name="OBX.3.3" type="xs:NCName"/>
  <xs:element name="OBX.3.6" type="xs:NCName"/>
  <xs:element name="OBX.5">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBX.5.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBX.5.1" type="xs:string"/>
  <xs:element name="OBX.7" type="xs:string"/>
  <xs:element name="OBX.11" type="xs:NCName"/>
  <xs:element name="OBX.14" type="xs:integer"/>
  <xs:element name="OBX.15">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBX.15.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBX.15.1" type="xs:NCName"/>
  <xs:element name="OBX.16">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="OBX.16.1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="OBX.16.1" type="xs:NCName"/>
</xs:schema>

=== YesItIsTrue/repo1/Batch-Runs/Apps/HL7/bin/HL7_XML_Files/DONT_TOUCH/HL7_MPA.xml
<?xml version="1.0" encoding="UTF-8"?>
<HL7 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///c:/apps/HL7/src/HL7_XML_Files/DONT_TOUCH/HL7_MPA.xsd">
	<ORU_R01>
		<MSH>
			<MSH.1><!--00001: Field Separator-->|<!--Segment="\u000D" Element="|"--></MSH.1>
			<MSH.2><!--00002: Encoding Characters-->^~\&amp;<!--Component="^" Repeat="~" Escape="\" Subcomponent="&"--></MSH.2>
			<MSH.3><!--00003: Sending Application-->
				<MSH.3.1><!--HD-1: Namespace ID-->DDI</MSH.3.1>
			</MSH.3>
			<MSH.4><!--00004: Sending Facility-->
				<MSH.4.1><!--HD-1: Namespace ID-->DDI</MSH.4.1>
			</MSH.4>
			<MSH.5><!--00005: Receiving Application-->
				<MSH.5.1><!--HD-1: Namespace ID-->DNA Lab</MSH.5.1>
				<MSH.5.2><!--HD-2: Universal ID-->DNALab</MSH.5.2>
			</MSH.5>
			<MSH.6><!--00006: Receiving Facility-->
				<MSH.6.1><!--HD-1: Namespace ID-->DNA Lab</MSH.6.1>
				<MSH.6.2><!--HD-2: Universal ID-->DNALab</MSH.6.2>
			</MSH.6>
			<MSH.7><!--00007: Date/Time of Message-->20170221181620<!--2017-02-21T18:16:20--></MSH.7>
			<MSH.9><!--00009: Message Type-->
				<MSH.9.1><!--00009: Message Code-->ORU<!--Observation result/unsolicited--></MSH.9.1>
				<MSH.9.2><!--00009: Trigger Event-->R01<!--ORU/ACK - Unsolicited transmission of an observation--></MSH.9.2>
			</MSH.9>
			<MSH.11><!--00011: Processing ID-->
				<MSH.11.1><!--PT-1: Processing ID-->P<!--Production--></MSH.11.1>
			</MSH.11>
			<MSH.12><!--00012: Version ID-->2.3<!--Release 2.3 March 1997--></MSH.12>
			<MSH.15><!--00015: Accept Acknowledgment Type-->NE<!--Never--></MSH.15>
		</MSH>
		<PID>
			<PID.1><!--00104: Set ID - PID-->1</PID.1>
			<PID.3><!--00106: Patient ID (Internal ID)-->
				<PID.3.1><!--CX-1: ID Number-->LINCOLN-A-00014</PID.3.1>
			</PID.3>
			<PID.5><!--00108: Patient Name-->
				<PID.5.1><!--XPN-1: Family Name-->
					<PID.5.1.1><!--Z_P9-1: Last name prefix-->Luttrell</PID.5.1.1>
				</PID.5.1>
				<PID.5.2><!--XPN-2: Given Name-->Robert</PID.5.2>
				<PID.5.3><!--XPN-3: Second and Further Given Names or Initials Thereof-->J</PID.5.3>
			</PID.5>
			<PID.7><!--00110: Date/Time of Birth-->19571021<!--1957-10-21--></PID.7>
			<PID.8><!--00111: Sex-->M<!--Male--></PID.8>
			<PID.9><!--00112: Patient Alias-->
				<PID.9.1><!--XPN-1: Family Name-->
					<PID.9.1.1><!--Z_P9-1: Last name prefix-->Ab</PID.9.1.1>
				</PID.9.1>
			</PID.9>
			<PID.11><!--00114: Patient Address-->
				<PID.11.1><!--XAD-1: Street Address-->101 Main</PID.11.1>
				<PID.11.2><!--XAD-2: Other Designation-->Apt 201</PID.11.2>
				<PID.11.3><!--XAD-3: City-->WALNUT CREEK</PID.11.3>
				<PID.11.4><!--XAD-4: State or Province-->CA</PID.11.4>
				<PID.11.5><!--XAD-5: Zip or Postal Code-->94595</PID.11.5>
			</PID.11>
			<PID.12><!--00115: County Code-->USA</PID.12>
			<PID.13><!--00116: Phone Number - Home-->
				<PID.13.1><!--XTN-1: Telephone Number-->510-123-4567</PID.13.1>
			</PID.13>
			<PID.14><!--00117: Phone Number - Business-->
				<PID.14.1><!--XTN-1: Telephone Number-->207-787-2000</PID.14.1>
			</PID.14>
			<PID.19><!--00122: SSN Number - Patient-->218688662</PID.19>
			<PID.30><!--00741: Patient Death Indicator-->N<!--No--></PID.30>
		</PID>
		<PV1>
			<PV1.1><!--00131: Set ID - PV1-->1</PV1.1>
			<PV1.3><!--00133: Assigned Patient Location-->
				<PV1.3.4><!--PL-4: Facility-->
					<PV1.3.4.1><!--HD-1: Namespace ID-->Clinic</PV1.3.4.1>
					<PV1.3.4.2><!--HD-2: Universal ID-->12345</PV1.3.4.2>
				</PV1.3.4>
			</PV1.3>
			<PV1.7><!--00137: Attending Doctor-->
				<PV1.7.2><!--XCN-2: Family Name-->
					<PV1.7.2.1><!--Z_P9-1: Last name prefix-->Pepper</PV1.7.2.1>
				</PV1.7.2>
				<PV1.7.3><!--XCN-3: Given Name-->Dr</PV1.7.3>
			</PV1.7>
			<PV1.19><!--00149: Visit Number-->
				<PV1.19.1><!--CX-1: ID Number-->B170125-2397-1</PV1.19.1>
			</PV1.19>
			<PV1.50><!--00180: Alternate Visit ID-->
				<PV1.50.1><!--CX-1: ID Number-->170125-2397</PV1.50.1>
			</PV1.50>
		</PV1>
		<ORC>
			<ORC.1><!--00215: Order Control-->RE<!--Observations to follow--></ORC.1>
			<ORC.3><!--00217: Filler Order Number-->
				<ORC.3.1><!--EI-1: Entity Identifier-->B170125-2397-1</ORC.3.1>
			</ORC.3>
			<ORC.4><!--00218: Placer Group Number-->
				<ORC.4.1><!--EI-1: Entity Identifier-->1</ORC.4.1>
			</ORC.4>
			<ORC.7><!--00221: Quantity/Timing--></ORC.7>
			<ORC.12><!--00226: Ordering Provider-->
				<ORC.12.2><!--XCN-2: Family Name-->
					<ORC.12.2.1><!--Z_P9-1: Last name prefix-->Pepper</ORC.12.2.1>
				</ORC.12.2>
				<ORC.12.3><!--XCN-3: Given Name-->Dr</ORC.12.3>
			</ORC.12>
			<ORC.13><!--00227: Enterer's Location-->
				<ORC.13.4><!--PL-4: Facility-->
					<ORC.13.4.1><!--HD-1: Namespace ID-->Clinic</ORC.13.4.1>
					<ORC.13.4.2><!--HD-2: Universal ID-->12345</ORC.13.4.2>
				</ORC.13.4>
			</ORC.13>
			<ORC.20>1</ORC.20>
		</ORC>
		<NTE>
			<NTE.1><!--00096: Set ID - NTE-->1</NTE.1>
			<NTE.3><!--00098: Comment-->Comments Area - for notes</NTE.3>
		</NTE>
		<ZCF>
			<ZCF.1>Tracking Number:</ZCF.1>
			<ZCF.3>Medicare Number 2:</ZCF.3>
			<ZCF.5>Medicare Number 1:</ZCF.5>
			<ZCF.7>County:</ZCF.7>
			<ZCF.9>Last Name:</ZCF.9>
			<ZCF.10>La'Name</ZCF.10>
			<ZCF.11>First Name:</ZCF.11>
			<ZCF.12>La'name</ZCF.12>
			<ZCF.13>SSN:</ZCF.13>
			<ZCF.14>218688662</ZCF.14>
			<ZCF.15>DOB:</ZCF.15>
			<ZCF.16>19571021</ZCF.16>
			<ZCF.17>Relationship to Patient:</ZCF.17>
			<ZCF.18>Parent</ZCF.18>
			<ZCF.19>Address:</ZCF.19>
			<ZCF.20>114 Road Rd</ZCF.20>
			<ZCF.21>City:</ZCF.21>
			<ZCF.22>Cityville</ZCF.22>
			<ZCF.23>State:</ZCF.23>
			<ZCF.24>ID</ZCF.24>
			<ZCF.25>Zip:</ZCF.25>
			<ZCF.26>12345</ZCF.26>
			<ZCF.27>Client Reference #:</ZCF.27>
			<ZCF.28>MD-123456</ZCF.28>
			<ZCF.29>Check No:</ZCF.29>
			<ZCF.31>Hold Reason:</ZCF.31>
			<ZCF.33>Check Amount $:</ZCF.33>
			<ZCF.35>Accessioned By:</ZCF.35>
		</ZCF>
		<OBR>
			<OBR.1><!--00237: Set ID - OBR-->1</OBR.1>
			<OBR.3><!--00217: Filler Order Number-->
				<OBR.3.1><!--EI-1: Entity Identifier-->B170125-2397-1</OBR.3.1>
			</OBR.3>
			<OBR.4><!--00238: Universal Service Identifier-->
				<OBR.4.1><!--CE-1: Identifier-->rs10380</OBR.4.1>
				<OBR.4.2><!--CE-2: Text-->MTRR/H595Y</OBR.4.2>
			</OBR.4>
			<OBR.5><!--00239: Priority-->R</OBR.5>
			<OBR.7><!--00241: Observation Date/Time-->20170117000000<!--2017-01-17--></OBR.7>
			<OBR.15><!--00249: Specimen Source-->
				<OBR.15.1><!--CM-1-->Blood</OBR.15.1>
			</OBR.15>
			<OBR.16><!--00226: Ordering Provider-->
				<OBR.16.2><!--XCN-2: Family Name-->
					<OBR.16.2.1><!--Z_P9-1: Last name prefix-->Pepper</OBR.16.2.1>
				</OBR.16.2>
				<OBR.16.3><!--XCN-3: Given Name-->Dr</OBR.16.3>
			</OBR.16>
			<OBR.24><!--00257: Diagnostic Serv Sect ID-->DDI</OBR.24>
			<OBR.25><!--00258: Result Status-->F<!--Final results; results stored and verified. Can only be changed with a corrected result.--></OBR.25>
			<OBR.27><!--00221: Quantity/Timing-->
				<OBR.27.6><!--TQ-6: Priority-->R</OBR.27.6>
			</OBR.27>
			<OBR.29><!--00261: Parent Number-->
				<OBR.29.1><!--CM-1-->170125-2397</OBR.29.1>
			</OBR.29>
			<OBR.30><!--00262: Transportation Mode-->PC</OBR.30>
			<OBR.51>PATIENT</OBR.51>
		</OBR>
		<OBX>
			<OBX.1><!--00569: Set ID - OBX-->1</OBX.1>
			<OBX.2><!--00570: Value Type-->ST<!--String Data--></OBX.2>
			<OBX.3><!--00571: Observation Identifier-->
				<OBX.3.1><!--CE-1: Identifier-->rs10380</OBX.3.1>
				<OBX.3.2><!--CE-2: Text-->rs10380</OBX.3.2>
				<OBX.3.3><!--CE-3: Name of Coding System-->DDI</OBX.3.3>
				<OBX.3.6><!--CE-6: Name of Alternate-->LN</OBX.3.6>
			</OBX.3>
			<OBX.5><!--00573: Observation Value-->
				<OBX.5.1>+/-</OBX.5.1>
			</OBX.5>
			<OBX.7><!--00575: References Range-->-/-</OBX.7>
			<OBX.11><!--00579: Observ Result Status-->F<!--Final results; Can only be changed with a corrected result.--></OBX.11>
			<OBX.14><!--00582: Date/Time of the Observation-->20170117000000<!--2017-01-17--></OBX.14>
			<OBX.15><!--00583: Producer's ID-->
				<OBX.15.1><!--CE-1: Identifier-->DDI</OBX.15.1>
			</OBX.15>
			<OBX.16><!--00584: Responsible Observer-->
				<OBX.16.1><!--XCN-1: ID Number-->DDI-IT1</OBX.16.1>
			</OBX.16>
		</OBX>
		<OBX>
			<OBX.1><!--00569: Set ID - OBX-->2</OBX.1>
			<OBX.2><!--00570: Value Type-->ST<!--String Data--></OBX.2>
			<OBX.3><!--00571: Observation Identifier-->
				<OBX.3.1><!--CE-1: Identifier-->rs10380_call</OBX.3.1>
				<OBX.3.2><!--CE-2: Text-->rs10380_call</OBX.3.2>
				<OBX.3.3><!--CE-3: Name of Coding System-->DDI</OBX.3.3>
				<OBX.3.6><!--CE-6: Name of Alternate-->LN</OBX.3.6>
			</OBX.3>
			<OBX.5><!--00573: Observation Value-->
				<OBX.5.1>Hetero</OBX.5.1>
			</OBX.5>
			<OBX.11><!--00579: Observ Result Status-->F<!--Final results; Can only be changed with a corrected result.--></OBX.11>
			<OBX.14><!--00582: Date/Time of the Observation-->20170117000000<!--2017-01-17--></OBX.14>
			<OBX.15><!--00583: Producer's ID-->
				<OBX.15.1><!--CE-1: Identifier-->DDI</OBX.15.1>
			</OBX.15>
			<OBX.16><!--00584: Responsible Observer-->
				<OBX.16.1><!--XCN-1: ID Number-->DDI-IT1</OBX.16.1>
			</OBX.16>
		</OBX>
		<OBR>
			<OBR.1><!--00237: Set ID - OBR-->2</OBR.1>
			<OBR.3><!--00217: Filler Order Number-->
				<OBR.3.1><!--EI-1: Entity Identifier-->B170125-2397-1</OBR.3.1>
			</OBR.3>
			<OBR.4><!--00238: Universal Service Identifier-->
				<OBR.4.1><!--CE-1: Identifier-->rs162036</OBR.4.1>
				<OBR.4.2><!--CE-2: Text-->MTRR/K350A</OBR.4.2>
			</OBR.4>
			<OBR.5><!--00239: Priority-->R</OBR.5>
			<OBR.7><!--00241: Observation Date/Time-->20170117000000<!--2017-01-17--></OBR.7>
			<OBR.10><!--00244: Collector Identifier-->
				<OBR.10.1><!--XCN-1: ID Number-->DDI-IT1</OBR.10.1>
			</OBR.10>
			<OBR.15><!--00249: Specimen Source-->
				<OBR.15.1><!--CM-1-->Blood</OBR.15.1>
			</OBR.15>
			<OBR.16><!--00226: Ordering Provider-->
				<OBR.16.2><!--XCN-2: Family Name-->
